//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualWallet.BUSINESS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualWallet.BUSINESS.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been blocked and cannot perform this task..
        /// </summary>
        internal static string AccountBlocked {
            get {
                return ResourceManager.GetString("AccountBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardholder name does not match..
        /// </summary>
        internal static string CardHolderNameMismatch {
            get {
                return ResourceManager.GetString("CardHolderNameMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card not found..
        /// </summary>
        internal static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment with id={0} doesn&apos;t exist..
        /// </summary>
        internal static string CommentNotFound {
            get {
                return ResourceManager.GetString("CommentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVV number does not match..
        /// </summary>
        internal static string CVVMismatch {
            get {
                return ResourceManager.GetString("CVVMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is already taken..
        /// </summary>
        internal static string EmailTaken {
            get {
                return ResourceManager.GetString("EmailTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only admins can perform this action!.
        /// </summary>
        internal static string ErrorMessageNotAdmin {
            get {
                return ResourceManager.GetString("ErrorMessageNotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already admin..
        /// </summary>
        internal static string ExceptionMessageAlreadyAdmin {
            get {
                return ResourceManager.GetString("ExceptionMessageAlreadyAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already not an admin..
        /// </summary>
        internal static string ExceptionMessageAlreadyNotAdmin {
            get {
                return ResourceManager.GetString("ExceptionMessageAlreadyNotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id must be positive integer!.
        /// </summary>
        internal static string ExceptionMessageIdMustBePositive {
            get {
                return ResourceManager.GetString("ExceptionMessageIdMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t exist!.
        /// </summary>
        internal static string ExceptionMessageUserNotExist {
            get {
                return ResourceManager.GetString("ExceptionMessageUserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id {0} doesn&apos;t exist!.
        /// </summary>
        internal static string ExceptionMessageUserWithIdNotExist {
            get {
                return ResourceManager.GetString("ExceptionMessageUserWithIdNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with username {0} doesn&apos;t exist!.
        /// </summary>
        internal static string ExceptionMessageUserWithUsernameNotExist {
            get {
                return ResourceManager.GetString("ExceptionMessageUserWithUsernameNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External payment processor failed to process the deposit..
        /// </summary>
        internal static string ExternalDepositFailure {
            get {
                return ResourceManager.GetString("ExternalDepositFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External payment processor failed to process the withdrawal..
        /// </summary>
        internal static string ExternalWithdrawalFailure {
            get {
                return ResourceManager.GetString("ExternalWithdrawalFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve Payment Processor Token..
        /// </summary>
        internal static string FailedToRetrievePaymentProcessorToken {
            get {
                return ResourceManager.GetString("FailedToRetrievePaymentProcessorToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials: &apos; Username: {0} and Password: {1} &apos; are incorrect..
        /// </summary>
        internal static string IncorrectCredentials {
            get {
                return ResourceManager.GetString("IncorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds in the real card..
        /// </summary>
        internal static string InsufficientRealCardFunds {
            get {
                return ResourceManager.GetString("InsufficientRealCardFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds in the wallet..
        /// </summary>
        internal static string InsufficientWalletFunds {
            get {
                return ResourceManager.GetString("InsufficientWalletFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials are invalid..
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deposit amount must be greater than zero..
        /// </summary>
        internal static string InvalidDepositAmount {
            get {
                return ResourceManager.GetString("InvalidDepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user information..
        /// </summary>
        internal static string InvalidUserInformation {
            get {
                return ResourceManager.GetString("InvalidUserInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid wallet information..
        /// </summary>
        internal static string InvalidWalletInformation {
            get {
                return ResourceManager.GetString("InvalidWalletInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The withdrawal amount must be greater than zero..
        /// </summary>
        internal static string InvalidWithdrawalAmount {
            get {
                return ResourceManager.GetString("InvalidWithdrawalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough funds in the card..
        /// </summary>
        internal static string NoCardsFound {
            get {
                return ResourceManager.GetString("NoCardsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post with id={0} doesn&apos;t exist..
        /// </summary>
        internal static string PostNotFound {
            get {
                return ResourceManager.GetString("PostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real card not found..
        /// </summary>
        internal static string RealCardNotFound {
            get {
                return ResourceManager.GetString("RealCardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real card associated with this payment processor token not found..
        /// </summary>
        internal static string RealCardTokenNotFound {
            get {
                return ResourceManager.GetString("RealCardTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this task..
        /// </summary>
        internal static string UnauthorizedAdminTask {
            get {
                return ResourceManager.GetString("UnauthorizedAdminTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The card and wallet must belong to the same user..
        /// </summary>
        internal static string UnauthorizedCardWallet {
            get {
                return ResourceManager.GetString("UnauthorizedCardWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this task..
        /// </summary>
        internal static string UnauthorizedTask {
            get {
                return ResourceManager.GetString("UnauthorizedTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already added to wallet..
        /// </summary>
        internal static string UserIsAlreadyAddedToWallet {
            get {
                return ResourceManager.GetString("UserIsAlreadyAddedToWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username &apos;{0}&apos; is already taken..
        /// </summary>
        internal static string UsernameTaken {
            get {
                return ResourceManager.GetString("UsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with id={0} doesn&apos;t exist..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet is not empty!.
        /// </summary>
        internal static string WalletNotEmpty {
            get {
                return ResourceManager.GetString("WalletNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet not found..
        /// </summary>
        internal static string WalletNotFound {
            get {
                return ResourceManager.GetString("WalletNotFound", resourceCulture);
            }
        }
    }
}
