services:
  # PostgreSQL Database Service
  db:
    image: "postgres:13"
    container_name: "postgres-db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrong!Passw0rd
      POSTGRES_DB: VirtualWalletDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "virtualwallet-app"
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=VirtualWalletDB;Username=postgres;Password=YourStrong!Passw0rd
    networks:
      - app-network

volumes:
  pgdata:
    driver: local

networks:
  app-network:
    driver: bridge
