version: '3.8'

services:
  # SQL Server Database Service
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: "sqlserver-db"
    environment:
      - SA_PASSWORD=YourStrong!Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"  # Exposing SQL Server on the default port
    volumes:
      - sqlvolume:/var/opt/mssql  # Persist database data on the host system

  # Application Service
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Use the Dockerfile from the root of the project directory
    container_name: "virtualwallet-app"
    ports:
      - "8080:80"  # Map port 80 inside the container to port 8080 on the host
    depends_on:
      - db  # Ensure the database service starts before the application
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=VirtualWalletDB;User ID=sa;Password=YourStrong!Passw0rd;

volumes:
  sqlvolume:
    driver: local  # Persist database data using a local volume
